services:
  - type: web
    name: aptitude-generator
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    healthCheckPath: /
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      # Uncomment and set only if you actually use email features in config.py
      # - key: MAIL_SERVER
      #   value: smtp.example.com
      # - key: MAIL_PORT
      #   value: "587"
      # - key: MAIL_USE_TLS
      #   value: "true"
      # - key: MAIL_USERNAME
      #   value: ""
      # - key: MAIL_PASSWORD
      #   value: ""
      # - key: MAIL_DEFAULT_SENDER
      #   value: "noreply@example.com"
